// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEP4uCoLRprBYXFzA55xaCogbBCYKOtBs',
    appId: '1:511512504118:web:f8c855bd006f602ef17597',
    messagingSenderId: '511512504118',
    projectId: 'cyberlog-7d5ff',
    authDomain: 'cyberlog-7d5ff.firebaseapp.com',
    storageBucket: 'cyberlog-7d5ff.firebasestorage.app',
    measurementId: 'G-E2KXB1VWTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApnxY6j5kLZas2H7OR8xg5E7PuFeD7s64',
    appId: '1:511512504118:android:13833fd7a25faeb7f17597',
    messagingSenderId: '511512504118',
    projectId: 'cyberlog-7d5ff',
    storageBucket: 'cyberlog-7d5ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9l0GYBc8mw2Fnb60vtaM_MS50DcvSggc',
    appId: '1:511512504118:ios:4a7fd4ea4bce6eeaf17597',
    messagingSenderId: '511512504118',
    projectId: 'cyberlog-7d5ff',
    storageBucket: 'cyberlog-7d5ff.firebasestorage.app',
    iosBundleId: 'com.example.cyberlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9l0GYBc8mw2Fnb60vtaM_MS50DcvSggc',
    appId: '1:511512504118:ios:4a7fd4ea4bce6eeaf17597',
    messagingSenderId: '511512504118',
    projectId: 'cyberlog-7d5ff',
    storageBucket: 'cyberlog-7d5ff.firebasestorage.app',
    iosBundleId: 'com.example.cyberlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEP4uCoLRprBYXFzA55xaCogbBCYKOtBs',
    appId: '1:511512504118:web:c1f6e52cf5779b5cf17597',
    messagingSenderId: '511512504118',
    projectId: 'cyberlog-7d5ff',
    authDomain: 'cyberlog-7d5ff.firebaseapp.com',
    storageBucket: 'cyberlog-7d5ff.firebasestorage.app',
    measurementId: 'G-F12EDX0BDQ',
  );
}
